//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\GitHub\sql-server-rest-api\RestApi\OData\ApplyTranslator.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IApplyTranslatorListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ApplyTranslatorBaseListener : IApplyTranslatorListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplyTranslatorParser.apply"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterApply([NotNull] ApplyTranslatorParser.ApplyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplyTranslatorParser.apply"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitApply([NotNull] ApplyTranslatorParser.ApplyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplyTranslatorParser.columns"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumns([NotNull] ApplyTranslatorParser.ColumnsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplyTranslatorParser.columns"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumns([NotNull] ApplyTranslatorParser.ColumnsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplyTranslatorParser.ids"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIds([NotNull] ApplyTranslatorParser.IdsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplyTranslatorParser.ids"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIds([NotNull] ApplyTranslatorParser.IdsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplyTranslatorParser.aggregates"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggregates([NotNull] ApplyTranslatorParser.AggregatesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplyTranslatorParser.aggregates"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggregates([NotNull] ApplyTranslatorParser.AggregatesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplyTranslatorParser.aggregate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggregate([NotNull] ApplyTranslatorParser.AggregateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplyTranslatorParser.aggregate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggregate([NotNull] ApplyTranslatorParser.AggregateContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
