//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\GitHub\sql-server-rest-api\RestApi\OData\ApplyTranslator.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ApplyTranslatorLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, OP=8, ID=9, WS=10;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "OP", "ID", "WS"
	};


	public ApplyTranslatorLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ApplyTranslatorLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'groupBy'", "'('", "','", "')'", "'aggregate('", "'with'", "'as'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, "OP", "ID", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ApplyTranslator.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ApplyTranslatorLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\f', 'Y', '\b', '\x1', '\x4', '\x2', '\t', '\x2', '\x4', 
		'\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', 
		'\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', 
		'\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', 
		'\v', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', 'J', '\n', '\t', '\x3', 
		'\n', '\x3', '\n', '\a', '\n', 'N', '\n', '\n', '\f', '\n', '\xE', '\n', 
		'Q', '\v', '\n', '\x3', '\v', '\x6', '\v', 'T', '\n', '\v', '\r', '\v', 
		'\xE', '\v', 'U', '\x3', '\v', '\x3', '\v', '\x2', '\x2', '\f', '\x3', 
		'\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', 
		'\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x3', '\x2', '\x5', 
		'\x6', '\x2', '%', '%', '\x42', '\\', '\x61', '\x61', '\x63', '|', '\a', 
		'\x2', '%', '%', '\x32', ';', '\x42', '\\', '\x61', '\x61', '\x63', '|', 
		'\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', '^', '\x2', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x3', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '\x1F', '\x3', '\x2', '\x2', '\x2', '\a', 
		'!', '\x3', '\x2', '\x2', '\x2', '\t', '#', '\x3', '\x2', '\x2', '\x2', 
		'\v', '%', '\x3', '\x2', '\x2', '\x2', '\r', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\xF', '\x35', '\x3', '\x2', '\x2', '\x2', '\x11', 'I', '\x3', 
		'\x2', '\x2', '\x2', '\x13', 'K', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'S', '\x3', '\x2', '\x2', '\x2', '\x17', '\x18', '\a', 'i', '\x2', '\x2', 
		'\x18', '\x19', '\a', 't', '\x2', '\x2', '\x19', '\x1A', '\a', 'q', '\x2', 
		'\x2', '\x1A', '\x1B', '\a', 'w', '\x2', '\x2', '\x1B', '\x1C', '\a', 
		'r', '\x2', '\x2', '\x1C', '\x1D', '\a', '\x44', '\x2', '\x2', '\x1D', 
		'\x1E', '\a', '{', '\x2', '\x2', '\x1E', '\x4', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', ' ', '\a', '*', '\x2', '\x2', ' ', '\x6', '\x3', '\x2', '\x2', 
		'\x2', '!', '\"', '\a', '.', '\x2', '\x2', '\"', '\b', '\x3', '\x2', '\x2', 
		'\x2', '#', '$', '\a', '+', '\x2', '\x2', '$', '\n', '\x3', '\x2', '\x2', 
		'\x2', '%', '&', '\a', '\x63', '\x2', '\x2', '&', '\'', '\a', 'i', '\x2', 
		'\x2', '\'', '(', '\a', 'i', '\x2', '\x2', '(', ')', '\a', 't', '\x2', 
		'\x2', ')', '*', '\a', 'g', '\x2', '\x2', '*', '+', '\a', 'i', '\x2', 
		'\x2', '+', ',', '\a', '\x63', '\x2', '\x2', ',', '-', '\a', 'v', '\x2', 
		'\x2', '-', '.', '\a', 'g', '\x2', '\x2', '.', '/', '\a', '*', '\x2', 
		'\x2', '/', '\f', '\x3', '\x2', '\x2', '\x2', '\x30', '\x31', '\a', 'y', 
		'\x2', '\x2', '\x31', '\x32', '\a', 'k', '\x2', '\x2', '\x32', '\x33', 
		'\a', 'v', '\x2', '\x2', '\x33', '\x34', '\a', 'j', '\x2', '\x2', '\x34', 
		'\xE', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', '\x63', '\x2', 
		'\x2', '\x36', '\x37', '\a', 'u', '\x2', '\x2', '\x37', '\x10', '\x3', 
		'\x2', '\x2', '\x2', '\x38', '\x39', '\a', 'u', '\x2', '\x2', '\x39', 
		':', '\a', 'w', '\x2', '\x2', ':', 'J', '\a', 'o', '\x2', '\x2', ';', 
		'<', '\a', '\x63', '\x2', '\x2', '<', '=', '\a', 'x', '\x2', '\x2', '=', 
		'J', '\a', 'i', '\x2', '\x2', '>', '?', '\a', 'o', '\x2', '\x2', '?', 
		'@', '\a', 'k', '\x2', '\x2', '@', 'J', '\a', 'p', '\x2', '\x2', '\x41', 
		'\x42', '\a', 'o', '\x2', '\x2', '\x42', '\x43', '\a', '\x63', '\x2', 
		'\x2', '\x43', 'J', '\a', 'z', '\x2', '\x2', '\x44', '\x45', '\a', '\x65', 
		'\x2', '\x2', '\x45', '\x46', '\a', 'q', '\x2', '\x2', '\x46', 'G', '\a', 
		'w', '\x2', '\x2', 'G', 'H', '\a', 'p', '\x2', '\x2', 'H', 'J', '\a', 
		'v', '\x2', '\x2', 'I', '\x38', '\x3', '\x2', '\x2', '\x2', 'I', ';', 
		'\x3', '\x2', '\x2', '\x2', 'I', '>', '\x3', '\x2', '\x2', '\x2', 'I', 
		'\x41', '\x3', '\x2', '\x2', '\x2', 'I', '\x44', '\x3', '\x2', '\x2', 
		'\x2', 'J', '\x12', '\x3', '\x2', '\x2', '\x2', 'K', 'O', '\t', '\x2', 
		'\x2', '\x2', 'L', 'N', '\t', '\x3', '\x2', '\x2', 'M', 'L', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'Q', '\x3', '\x2', '\x2', '\x2', 'O', 'M', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'P', '\x3', '\x2', '\x2', '\x2', 'P', '\x14', '\x3', 
		'\x2', '\x2', '\x2', 'Q', 'O', '\x3', '\x2', '\x2', '\x2', 'R', 'T', '\t', 
		'\x4', '\x2', '\x2', 'S', 'R', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\x3', 
		'\x2', '\x2', '\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\x3', 
		'\x2', '\x2', '\x2', 'V', 'W', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\b', 
		'\v', '\x2', '\x2', 'X', '\x16', '\x3', '\x2', '\x2', '\x2', '\x6', '\x2', 
		'I', 'O', 'U', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
