//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\GitHub\sql-server-rest-api\RestApi\OData\ApplyTranslator.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ApplyTranslatorParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IApplyTranslatorListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplyTranslatorParser.apply"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterApply([NotNull] ApplyTranslatorParser.ApplyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplyTranslatorParser.apply"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitApply([NotNull] ApplyTranslatorParser.ApplyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplyTranslatorParser.columns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumns([NotNull] ApplyTranslatorParser.ColumnsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplyTranslatorParser.columns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumns([NotNull] ApplyTranslatorParser.ColumnsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplyTranslatorParser.ids"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIds([NotNull] ApplyTranslatorParser.IdsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplyTranslatorParser.ids"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIds([NotNull] ApplyTranslatorParser.IdsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplyTranslatorParser.aggregates"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggregates([NotNull] ApplyTranslatorParser.AggregatesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplyTranslatorParser.aggregates"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggregates([NotNull] ApplyTranslatorParser.AggregatesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplyTranslatorParser.aggregate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggregate([NotNull] ApplyTranslatorParser.AggregateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplyTranslatorParser.aggregate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggregate([NotNull] ApplyTranslatorParser.AggregateContext context);
}
